### PR TITLE
Code reorganization

### PR DESCRIPTION
**Pull request by iboates**
So this is going to be a rather bold PR. I have a colleague who _may_ be interested in helping to bring multi-GPU support to the project via Microsoft DeepSpeed, if they have time. In this vein I think that the repository could use a bit more structure to better support collaborative development. So I went ahead and re-organized the structure of the repo in a way that I think may be a bit easier to manage. All the actual code and the logic should be the exact same as version 0.6.9, just split across different files and folders. See the diagram below.

Untitled Diagram

Like I've said before I have a very limited knowledge of machine learning theory, so this is based on what I could figure out by looking at which classes were invoking which others. Let me know what you think about it.

### CODE REVIEW

**Comment by iboates** [comment]
I just realized that there is an error in the diagram and I forgot to save the diagram raw file... "dataset" is at the same level as "gan", not inside of it.

**Comment by lucidrains** [comment]
@iboates great effort! looks very corporate :)

I will take you up on this PR, but only after I finish adding one last feature and the code base is more solidified. as you can tell, I've organized it already in such a way that it is easy to separate into folders in the end

**Comment by lucidrains** [comment]
@iboates that last feature will be an integration with Deepspeed btw, you will get your wish :)

**Comment by NickAcPT** [comment]
> I just realized that there is an error in the diagram and I forgot to save the diagram raw file... "dataset" is at the same level as "gan", not inside of it.

Since the diagram was made in draw.io and it was embedded on the png file, you can just go to File -> Import and open that image.

**Pull request closed without merging**
